### ISSUE TITLE
Nuxt Build Error: No known conditions for "./node" specifier in "msw" package

### ISSUE THREAD

**Issue by snowdream** [snowdreamtech/vue-nuxt-element-template#2]
```
Run pnpm build && pnpm generate
  pnpm build && pnpm generate
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3

> vue-nuxt-element-template@0.1.0 build /home/runner/work/vue-nuxt-element-template/vue-nuxt-element-template
> MODE=prod nuxi build

[log] Nuxt 3.8.0 with Nitro [2](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:2).7.1
[info] Building client...
[info] vite v4.5.0 building for production...
[info] transforming...
[info] ✓ 1[3](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:3)1 modules transformed.
[info] ✓ built in [4](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:4).31s
Error:  [commonjs--resolver] No known conditions for "./node" specifier in "msw" package
Error:  Nuxt Build Error: No known conditions for "./node" specifier in "msw" package
  at e (node_modules/.pnpm/vite@4.[5](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:5).0_@types+node@18.18.7_sass@1.[6](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:6)9.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:25)
  at n (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.[7](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:8)_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb[8](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:9)a833[9](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:10).js:21445:646)
  at o (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:21445:[12](https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067#step:11:13)97)
  at resolveExportsOrImports (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28746:20)
  at resolveDeepImport (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28765:31)
  at tryNodeResolve (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
  at Object.resolveId (node_modules/.pnpm/vite@4.5.0_@types+node@18.18.7_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
  at node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

https://github.com/snowdreamtech/vue-nuxt-element-template/actions/runs/6663182217/job/18108684067

**Comment by peterleilei86** [comment]
Hey, I am trying to set up msw with Nuxt 3 but I am getting `Error: No known conditions for "./browser" specifier in "msw" package` error when running unit tests. I have exact same set up like yours. The only difference is I disabled `ssr` for my project and only use msw for browser. Are you able to add tests and run them successfully?
